### ISSUE TITLE
Create a single package that will include all existing packages for a single NuGet reference.

### ISSUE THREAD

**Issue by PTKu** [TcOpenGroup/TcOpen#115]

**Comment by jozefchmelar** [comment]
What should be a name of such package?

- TcOpen
- TcOpen.All
- TcOpen.Package
- TcOpen.Group

I'm going for  *TcOpen.Group*  :)

**Comment by PTKu** [comment]
@jozefchmelar 
Re-opening seems we are creating package, but not getting published.

**Comment by PTKu** [comment]
me bad... seems ok... was looking in wrong place
