### ISSUE TITLE
app cylinder do not work??

### ISSUE THREAD

**Issue by runtimevic** [TcOpenGroup/TcOpen#138]
Hello,
The app buttons do not work to send the cylinder to rest or work, and I don't know why?

<img width="1408" alt="Beckhoff_Inxton_TcOpen_not_" src="https://user-images.githubusercontent.com/53791834/119392963-ac028d80-bcd0-11eb-801a-647935da6ae0.PNG">

**Comment by PTKu** [comment]
I believe only the first instance of the cylinder is initialized. That is a sandbox application for testing the UI and so it is not designed to be fully functional. If you want to try you can initialize the other cylinders in `MAIN._defaultContext.Main()` along the lines of the one that is already there.

**Comment by PTKu** [comment]
@runtimevic closing here... feel free to reopen if you see it necessary
