### ISSUE TITLE
TcoTask should have OnErrorEntry() method that would be called only once in case of Error.

### ISSUE THREAD

**Issue by TomKovac** [TcOpenGroup/TcOpen#145]
OnTaskError() method should be refactored to OnError() or HasError()/it could be discussed/.

Protected OnErrorEntry() or similarly named method should be added, that would be called only at 'raising' Error state.
It could be called for example inside ThrowWhen() method, at the moment when error condition became TRUE.

**Comment by PTKu** [comment]
see https://github.com/TcOpenGroup/TcOpen/commit/980b724f3d0b49e807b8fec4ee5df4972cf2eb9e
