### ISSUE TITLE
TcoDiagnosis - diagnosis of software and hardware

### ISSUE THREAD

**Issue by philippleidig** [TcOpenGroup/TcOpen#153]
Are there already ideas for the implementation of a consistent diagnosis for software and hardware in the PLC? 

I am of the opinion that especially in these areas, a detailed diagnosis is considered to be very useful. 

- IPC / Hardware e.g. CPU usage, ...
- TwinCAT e.g. licensing, realtime info, ...
- EtherCAT / Fieldbus e.g. simple and in-depth
- Motion / Axes

Every EtherCAT slave with CoE can send messages to the TcEventLogger. Only by checking this box. However, these messages are only in German and English. It might be possible to use these messages for diagnostics as well.

![image](https://user-images.githubusercontent.com/45693860/120011766-efb20b80-bfde-11eb-9e06-b7a7ad2558c2.png)

**Comment by PTKu** [comment]
This is would be extremely valued @philippleidig.  Is there a way to set the 'enable sending Emergency' programmatically?  
It would be good if we have a clear idea, and maybe some default implementation of #140 (to see if/how we can integrate messaging in general etc.)
@philippleidig  when you feel like it you can create a branch for this issue and sketch some prototype... I will certainly join the effort :)

**Comment by philippleidig** [comment]
@PTKu, the "enable sending emergency" - flag can be activated for example from the PLC via CoE - Write at runtime ( 0x10F3:05 ) 

![image](https://user-images.githubusercontent.com/45693860/120105952-5f4d0580-c15b-11eb-8238-7c97c48e16ca.png)

I would prefer an EtherCAT diagnosis, for example, without linking variables to the hardware. Or a generic axis diagnosis for CoE and SoE purely based on AXIS_REF. I will give it some thought :)

**Comment by PTKu** [comment]
Hi @philippleidig I would leave this open... there have been other priorities but I would like to return to this at some point....

**Comment by PTKu** [comment]
@TomKovac this would be nice to consider for the HW diagnostics, would you mind having a look at it?
