### ISSUE TITLE
Possible UI for Twincat/BSD 

### ISSUE THREAD

**Issue by RGrabichler** [TcOpenGroup/TcOpen#158]
Does anyone plan or try to use the new Twincat/BSD from Beckhoff?

The Support in Munich told me, that roughly in 3th quarter they plan to support the Twincat HMI-Server TF2000.
Is this also possible or is there a way with the WPF- Framework?

Edit: P.S. Assigning was not intentionally

**Comment by PTKu** [comment]
😄 @RGrabichler, not a problem assigning... the team that is working intensively on this here like @TomKovac and @jozefchmelar soon others should join, we do not have experience with Beckhoff HMI as we always used only WPF based UI in our applications for the last 10 years (that eventually became inxton). So as I mentioned in the LinkedIn [article](https://www.linkedin.com/pulse/tcopen-open-source-twincat-3-peter-kurhajec/) we want to keep compatibility with Beckhoff HMI, but 
a) we do not have resources to invest in it, 
b) we do not have sufficient experience, 
c) we look for a maintainer that would be willing to take care of the Beckhoff HMI part of this project.

We will need to see
a) how are we going to test UI (unit and integration) 
b) how and if Beckhoff HMI will be suitable for CI/CD pipeline.

P.S: We are exploring Blazor technology that may work on BSD
P.S.2: yet another promising technology: https://github.com/AvaloniaUI/Avalonia 
P.S.3: You can still use existing WPF on separate hardware (PC) connected to Tc/BSD system.
