### ISSUE TITLE
TcoData MongoDB it doesn't work for me

### ISSUE THREAD

**Issue by runtimevic** [TcOpenGroup/TcOpen#178]
Hello,
TcoData MongoDB it doesn't work for me.
I put some photos so that it looks like I have it configured:

<img width="1189" alt="Beckhoff_TcOpen_MongoDB_StringConnection1" src="https://user-images.githubusercontent.com/53791834/121007089-f2a4bd00-c791-11eb-8c8c-3506fb4a8045.PNG">

<img width="1639" alt="Beckhoff_TcOpen_MongoDB_StringConnection2" src="https://user-images.githubusercontent.com/53791834/121007111-f7697100-c791-11eb-9365-662a35b82590.PNG">

**Comment by PTKu** [comment]
It's hard to say... from the pictures. Did you create the `TestDatabase` and `TestCollection` manually?

**Comment by runtimevic** [comment]
> It's hard to say... from the pictures. Did you create the `TestDatabase` and `TestCollection` manually?

Hello, @PTKu :
Yes create manually TestDatabase and TestCollection.

**Comment by PTKu** [comment]
You modified the unit test code. What is the unit test result when you run it?

**Comment by runtimevic** [comment]
> You modified the unit test code. What is the unit test result when you run it?

![Beckhoff_TcOpen_MongoDB_no_work](https://user-images.githubusercontent.com/53791834/121171775-39101f80-c857-11eb-8a20-1418253dcbf8.PNG)

**Comment by PTKu** [comment]
I think we will need to make an (online) meeting with the community to explain how to work with the repo and also we need to go through some concepts about testing (unit, sandbox, and integrations). 

You are running a sandbox application, but the set-up of the repo is made in the unit testing project, you would need to implement the repo in that WPF application for it to work.

**Comment by runtimevic** [comment]
> I think we will need to make an (online) meeting with the community to explain how to work with the repo and also we need to go through some concepts about testing (unit, sandbox, and integrations).
> 
> You are running a sandbox application, but the set-up of the repo is made in the unit testing project, you would need to implement the repo in that WPF application for it to work.

yes i think we need it, I'll be waiting for it.
thanks you Víctor

**Comment by jozefchmelar** [comment]
Is this issue resolved?

**Comment by runtimevic** [comment]
> ¿Se ha resuelto este problema?

Hello, 
I do not know how to add to the wpf the tcodata, hoping to have if there is in youtube or the project some example ...

**Comment by jozefchmelar** [comment]
Hola@runtimevic,
good idea about the video, or project example. I'll prepare some example!

**Comment by jozefchmelar** [comment]
@runtimevic I tried to write a tutorial here : https://github.com/TcOpenGroup/TcOpen.Hammer/tree/data_examples/HMI/Data 
And the project I'm using : 
https://github.com/TcOpenGroup/TcOpen.Hammer/tree/data_examples 

I'd appreciate your feedback on it... If I'll have some spare time I'll make a video too.

**Comment by runtimevic** [comment]
> @runtimevic I tried to write a tutorial here : https://github.com/TcOpenGroup/TcOpen.Hammer/tree/data_examples/HMI/Data
> And the project I'm using :
> https://github.com/TcOpenGroup/TcOpen.Hammer/tree/data_examples
> 
> I'd appreciate your feedback on it... If I'll have some spare time I'll make a video too.

@jozefchmelar ,
thank you very much, when I can I try it...
