### ISSUE TITLE
question TcOpen example sequencer not run

### ISSUE THREAD

**Issue by runtimevic** [TcOpenGroup/TcOpen#26]
Hello,
For the demo example of the sequencer to work, 
it is necessary to have something installed in the C:\Inxton folder?
Thanks you, Víctor.

**Comment by runtimevic** [comment]
> Hello,
> For the demo example of the sequencer to work,
> it is necessary to have something installed in the C:\Inxton folder?
> Thanks you, Víctor.

solved by adding license-default.xml

**Comment by runtimevic** [comment]
solved by adding license-default.xml

**Comment by PTKu** [comment]
Thanks for the question @runtimevic 
Just for future reference. Should anyone else come across this problem 
If you want to run inxton related code, you will need to get the free developer license here:

https://docs.inxton.com/#licencing
here is YT instruction video: 
https://www.youtube.com/watch?v=SdCjBbvDjP8
