### ISSUE TITLE
TcOpen_the_Vortex_Builder_does_not_exists?

### ISSUE THREAD

**Issue by runtimevic** [TcOpenGroup/TcOpen#261]
Hello, 
TcOpen_the_Vortex_Builder_does_not_exists?
I attach a photo to show it, how can it be fixed?
![TcOpen_the_Vortex_Builder_does_not_exists](https://user-images.githubusercontent.com/53791834/141292669-71c9ac52-bc98-4a5b-983c-d3a1ac1f59c2.PNG)

thanks

**Comment by runtimevic** [comment]
Hi @PTKu 
I have made a project from scratch to test and anyway I do not believe the libraries in Twincat, I am attaching a photo so you can see it
![TcOpen_the_Vortex_Builder_not_create_library](https://user-images.githubusercontent.com/53791834/141297083-d8b6f320-0da8-4f49-a3c9-bde831650a55.PNG)

I do not know how to fix it...

**Comment by runtimevic** [comment]
Hi @PTKu 
I have succeeded, the problem is that the PLC name cannot be given when adding the PLC project,
I attach a photo to show it.

![TcOpen_the_Vortex_Builder_OK_create_library](https://user-images.githubusercontent.com/53791834/141300396-14a3701b-ab4c-40d7-952e-277e662a19b8.PNG)

Now I can continue ...

**Comment by runtimevic** [comment]
Hi @PTKu ,
I've gotten stuck again
plc.MAIN._simpleContext, does not contain a definition,
I am attaching a photo so you can see it, how is it fixed?
![TcOpen_MAIN_does_not_contain_a_definition](https://user-images.githubusercontent.com/53791834/141305906-d390b004-58a0-4333-bd2f-9d5438205634.PNG)

**Comment by PTKu** [comment]
@runtimevic do you have an instance of SimpleContext in MAIN?
~~~
PROGRAM MAIN
VAR
      _simpleContext : SimpleContext;
END_VAR
~~~

If you do have it then you'll need to run inxton compiler again to refresh the twin project.
Let me know if that helps

**Comment by runtimevic** [comment]
> @runtimevic do you have an instance of SimpleContext in MAIN?
> 
> ```
> PROGRAM MAIN
> VAR
>       _simpleContext : SimpleContext;
> END_VAR
> ```
> 
> If you do have it then you'll need to run inxton compiler again to refresh the twin project. Let me know if that helps

Hello @PTKu ,
solved, recompile with Inxton,
Do you know how I can remove the errors from the GitHub project XaeTcOpen101, the first photo I have attached?
thanks

**Comment by PTKu** [comment]
@runtimevic  You should replace the string "your-ams-id" with the AMD ID of your target if it is the local you can assign 'null'

so at line 13:

~~~C#
// example:
static string AMS_ID = "192.168.0.2.1.1" ;
~~~

// if your target is local then
~~~C#
static string AMS_ID = null;
~~~

in file `/TcOpen101/TcOpenPlcConnector/Properties/Secrets.cs `

you'll need to fix

~~~ C#
public static class Secrets
{
     public const string pwd = -"your_elastic_password"-;
}
~~~

with

~~~ C#
public static class Secrets
{
     public const string pwd = "runtimevic elastic password";
}
~~~

I left the compile errors intentionally there to force fixing with proper values.

**Comment by runtimevic** [comment]
> @runtimevic You should replace the string "your-ams-id" with the AMD ID of your target if it is the local you can assign 'null'
> 
> so at line 13:
> 
> ```cs
> // example:
> static string AMS_ID = "192.168.0.2.1.1" ;
> ```
> 
> // if your target is local then
> 
> ```cs
> static string AMS_ID = null;
> ```
> 
> in file `/TcOpen101/TcOpenPlcConnector/Properties/Secrets.cs `
> 
> you'll need to fix
> 
> ```cs
> public static class Secrets
> {
>      public const string pwd = -"your_elastic_password"-;
> }
> ```
> 
> with
> 
> ```cs
> public static class Secrets
> {
>      public const string pwd = "runtimevic elastic password";
> }
> ```
> 
> I left the compile errors intentionally there to force fixing with proper values.

Hi @PTKu,

If everything you have sent me I already know, the problem is here:
var plc = new TcOpenPlcTwinController (
I am attaching a photo for you to see, that's what I don't know why it's wrong

<img width="2880" alt="TcOpen_not_compilePNG" src="https://user-images.githubusercontent.com/53791834/141644814-bf2764eb-4c85-4fe8-9bb4-1f3e36e42148.png">

**Comment by PTKu** [comment]
@runtimevic I thought you were asking about the compile errors from the first item in this thread.

The solution is missing the `*.g.cs` files that are generated by the compiler. If you get the message that the compiler does not exist... it is an issue with the VS. To workaround that problem you just open 'Package manager console' that should copy the compiler into right place. Then you should be able to run it using the extension. When I am able to I will sent you a screenshot.

**Comment by PTKu** [comment]
@runtimevic 
Open Package Manager Console:
![image](https://user-images.githubusercontent.com/61538034/141647428-204f27c4-7ae5-4e92-99ae-e8800a2eeccf.png)

In package manage you should find this:
![image](https://user-images.githubusercontent.com/61538034/141647463-c080507a-8c44-476e-afb4-e8bffcdf1409.png)

then run inxton compiler

**Comment by PTKu** [comment]
@runtimevic  you can also download the project with all binaries included [here](https://github.com/PTKu/TcOpen-Examples/releases/download/TcOpen101A/TcOpen-Examples.zip)

**Comment by runtimevic** [comment]
> @runtimevic Open Package Manager Console: ![image](https://user-images.githubusercontent.com/61538034/141647428-204f27c4-7ae5-4e92-99ae-e8800a2eeccf.png)
> 
> In package manage you should find this: ![image](https://user-images.githubusercontent.com/61538034/141647463-c080507a-8c44-476e-afb4-e8bffcdf1409.png)
> 
> then run inxton compiler

Hi @PTKu , 
all resolved OK, thank you very much for the quick response, 👍👍😉
Where do you download the ELK Elasticsearch, Logstash and Kibana executables from?
https://www.elastic.co/es/downloads/kibana
https://www.elastic.co/es/downloads/logstash
https://www.elastic.co/es/downloads/elasticsearch
of these links are downloaded?
Thank you so much, Víctor.

**Comment by PTKu** [comment]
@runtimevic Yes Victor you can download kibana and elasticsearch from those links... 
Close this issue at your discretion.
