### ISSUE TITLE
Enable individual Config for Actuator (Cylinder)

### ISSUE THREAD

**Issue by RGrabichler** [TcOpenGroup/TcOpen#280]
I tried to do and individual TimeOut config for a Cylinder like that.
![image](https://user-images.githubusercontent.com/33341896/144706449-329a40f0-3066-4549-a064-bc501e08a87b.png)
in a TcCore.TcoObject, similar to HammerProject
![image](https://user-images.githubusercontent.com/33341896/144706474-49c97a06-8dc7-4bc1-a85b-d9a740d6bdc6.png)
but it fails with a CheckPointer Fault.
![image](https://user-images.githubusercontent.com/33341896/144706505-6fd1e8d3-35e2-49ce-b5a7-f04152890a5a.png)

I used to have a Method, executed on first Cycle, to set Configs, Properties and Names on my Actuators.

Is it possible to do the same here,
or what is the preferred way to use individual Configs.

**Comment by PTKu** [comment]
I think in the extended block there is a need to call SUPER^() in the body of the FB
~~~iec
SUPER^(inoAtHomePos := inoAtHomePos, inoAtWorkPos := inoAtWorkPos, inoToHomePos := inoToHomePos, inoToWorkPos := inoToWorkPos);
~~~

@RGrabichler  let me know if that worked for you.
