### ISSUE TITLE
When you create an empty role in blazor it throws an exception

### ISSUE THREAD

**Issue by jozefchmelar** [TcOpenGroup/TcOpen#287]
**Describe the bug**

if i press, create new role, without a string it gets an exception

**To Reproduce**
1. Go to security tab in blazor app with admin rights
1. Click on create new role
1.exception

**Expected behavior**
no exception, button should not be clickable if there's no content
**Screenshots**

--reported by @RGrabichler

**Comment by PTKu** [comment]
@jozefchmelar is was this solved by  #297 ?

**Comment by jozefchmelar** [comment]
yes. closing
