### ISSUE TITLE
Scaffold project for Beckhoff's drives.

### ISSUE THREAD

**Issue by PTKu** [TcOpenGroup/TcOpen#29]

**Comment by runtimevic** [comment]
Hello,
 I think it could help to properly develop the component of a motion ptp axis, how can I be part of the team to perform it?
thank you, Víctor.

**Comment by PTKu** [comment]
Hola Victor fantastico.  Just sent you an invite to TcOpenGroup org. 
@TomKovac is cooking something, I just spoke to him, when he is able, he will post here the branch where he is working... you can then have a discussion around it. Thanks for the initiative, much appreciated.

**Comment by runtimevic** [comment]
> Hola Victor fantastico. Just sent you an invite to TcOpenGroup org.
> @TomKovac is cooking something, I just spoke to him, when he is able, he will post here the branch where he is working... you can then have a discussion around it. Thanks for the initiative, much appreciated.

I am already part of the TcOpen group, if you can add me to TcoBeckhoffDrives and also TcoPneumatics, I think I can collaborate in a positive way, thanks

**Comment by runtimevic** [comment]
> Hola Victor fantastico. Just sent you an invite to TcOpenGroup org.
> @TomKovac is cooking something, I just spoke to him, when he is able, he will post here the branch where he is working... you can then have a discussion around it. Thanks for the initiative, much appreciated.
 Hi Peter,
how I can get in touch with TomKovac?
thanks you.

**Comment by PTKu** [comment]
@runtimevic I sent you an invite to gitter for a quick comm channel. @TomKovac is there if you need a quick chat you can do it there.

**Comment by runtimevic** [comment]
> @runtimevic I sent you an invite to gitter for a quick comm channel. @TomKovac is there if you need a quick chat you can do it there.

I contacted by @TomKovac to gitter
thanks,
