### ISSUE TITLE
TcOpen101-3 TcoTask how to tame wild PLC cycle.question, operating modes (Home, Auto, Manual) with PackML and different types of cylinders

### ISSUE THREAD

**Issue by runtimevic** [TcOpenGroup/TcOpen#291]
Hello @PTKu ,
First of all, thanks for the videos, they are a great help to understand how TcOpen works.
.- With TcoCore.Task you perform, for example, the operating modes of the installation such as Home Ground, Automatic and Manual, my question would it be possible to integrate it with the OMAC PackML or PackML v2 (Packaging Machine State) libraries? It would be good to have an example with this type of libraries since with this we could cover a very good example for the operating modes with TcOpen and PackML ...
.- My other question or suggestion is that I think it would be better if the cylinder component could expand from a base cylinder to different types of cylinder, or have the different types of cylinders as components, or be able to configure them to behave according to your configuration. , since there may be in the projects that we can find cylinders without input position sensors or with sensors only at one end or have at both ends and the same for the outputs with a single output or with 2 outputs, with this the diagnosis It is also different because having or not having position sensor inputs changes the diagnosis ...
thanks you, Víctor.

**Comment by PTKu** [comment]
Hi @runtimevic `TcoTask` are as generic as possible to not impose limits for future scenarios; will come up with some other extensions to TcoTask in some future videos; I have some vague knowledge about OMAC PackML etc we can certainly extend to that realm in the future as well... 
As per the cylinder... it is an object that can be extended and the functions can be overridden. We may have a look into the parametrization aspect as well.
