### ISSUE TITLE
Add IdExist, CreateOrUpdate to ITcoCrud

### ISSUE THREAD

**Issue by kuh0005** [TcOpenGroup/TcOpen#315]

**Comment by jozefchmelar** [comment]
already implemented

**Comment by PTKu** [comment]
@jozefchmelar  is it or I am missing something? :D
![image](https://user-images.githubusercontent.com/61538034/150531434-565052a4-6eab-4c42-b0ea-3847c09afef5.png)

**Comment by jozefchmelar** [comment]
I'm sorry, it's a bit of a misunderstanding. - No wonder when there was zero info about the issue :) 

The ITcoCrud interface doesn't implement `CreateOrUpdate` or `IdExist`. However, the `TcoDataExchange` does contain implementations for such operations. 

Should `ITcoCrud` even implement such operations?  Right now it lives up to its name. 

We could have an additional interface, which extends from `ITcoCrud` which could implement those operations and even some more in case we need them. Then the TcoDataExchange would implement the extended interface.

**Comment by PTKu** [comment]
@kuh0005 is this really needed for some practical reasons?

**Comment by PTKu** [comment]
@kuh0005 closing this should it be needed feel free to reopen.
