### ISSUE TITLE
Diagnostics View 

### ISSUE THREAD

**Issue by RGrabichler** [TcOpenGroup/TcOpen#339]
A few things i noticed, which i am used to from other Diagnostics Views

- Auto Updating not working
- Acknowledged (or Rogered as u call it) Timestamp, so open Messsages can be shown
![image](https://user-images.githubusercontent.com/33341896/150928762-2a3f3273-7b66-4b09-b28f-8e96be87d8fe.png)

- in RenderableContentView property, to change default eMessageCategories
- Displaying like the 1000 last Messages with Filtering Function
- Ordering of Messages

Thanks guys

**Comment by Specter-13** [comment]
@RGrabichler hey I added some requested features to Diagnostics so if you have time, you can check it out. Look into PR #366.
When you use new sorting table, don't forget to add `services.AddTcoCoreExtensions();` to Startup.cs of your Blazor App.
If you have any questions or ideas, don't hesitate to contact me.

**Comment by RGrabichler** [comment]
Thanks, i will look at it soon and give my feedback.
