### ISSUE TITLE
Add Library Category for TcOpen

### ISSUE THREAD

**Issue by RGrabichler** [TcOpenGroup/TcOpen#346]
The Inxton Compiler automatically installs the TcOpen Librarys under the Category "Miscellaneous".

This is pretty simple to change with a xxx.libcat.xml Description, shown by Jakob Sagatowski.
[https://github.com/sagatowski/TwinCAT-LibraryCategories](https://github.com/sagatowski/TwinCAT-LibraryCategories)

**Comment by PTKu** [comment]
@RGrabichler good suggestion added to the task list of inxton team :)
