### ISSUE TITLE
Diagnostic view - Default category

### ISSUE THREAD

**Issue by jozefchmelar** [TcOpenGroup/TcOpen#357]
Add default category property to the view, so the programmer can define what category should display by default.
When you're at it also default depth could be useful as well.

Based on #339

**Comment by KevinLaurincik** [comment]
Now you can set DefaultCategory and DefaultDepth in blazor application.
![DiagnosticsRazor](https://user-images.githubusercontent.com/87848405/177715339-04686c2e-a314-4f25-af06-e2bbd42796a6.png)
