### ISSUE TITLE
Data manager view 

### ISSUE THREAD

**Issue by jozefchmelar** [TcOpenGroup/TcOpen#359]
The user would like to see the data stored in the DB, find a record with an ID and see the latest records in DB. 
Create a view that will utilize RenderableContentControl to display the stored data and add controls that will enable pagination, filtering and searching.

**Comment by PTKu** [comment]
@Specter-13 see the implementation in wpf https://github.com/TcOpenGroup/TcOpen/tree/dev/src/TcoData/src/Wpf/TcoData.Wpf/Data/Data
