### ISSUE TITLE
Rendering without presentation type

### ISSUE THREAD

**Issue by jozefchmelar** [TcOpenGroup/TcOpen#360]
Current behavior : 
If there's no presentation type specified, the base type will be rendered, even though there's a defined view for the type.
For example if I render TcoTask without presentation type, every single property will be rendered separately, even though I created TcoTaskView elsewhere. 

Expected behavior :  The TcoTaskView will render.

**Comment by PTKu** [comment]
/

**Comment by PTKu** [comment]
this should be solved in ivf
