### ISSUE TITLE
BlazorApp crashes with "Diagnostics" View

### ISSUE THREAD

**Issue by RGrabichler** [TcOpenGroup/TcOpen#390]
Blazor crashes with unhandled Exception, when clicking on DiagnosticsView
This is dev-Branch
![image](https://user-images.githubusercontent.com/33341896/159118141-4c430876-ed53-4bf9-8c65-aa068bf862f2.png)

This is implementation 
![image](https://user-images.githubusercontent.com/33341896/159118162-b46647e3-98ae-4510-be11-2b97813f2fe9.png)

**Comment by Specter-13** [comment]
@RGrabichler @PTKu  Hello, this is not bug, as I wrote in #366, you forgot to add to Startup.cs:
 `services.AddTcoCoreExtensions();`
which will enable Datagrid component in Diagnostics to enable filtering and other features.
Let me know, if this will solve your issue.

**Comment by RGrabichler** [comment]
@Specter-13  Adding the `services.AddTcoCoreExtensions();` and adding `using TcOpen.Inxton.TcoCore.Blazor.Extensions;` solved the issues.

I noticed, in the TcHammer.Blazor Project this is still missing.
Roman
