### ISSUE TITLE
NU1701 warning after TcoCoreConnector installation

### ISSUE THREAD

**Issue by rruiter87** [TcOpenGroup/TcOpen#403]
After installing TcoCoreConnector using the [instructions](https://docs.tcopengroup.org/articles/TcOpenFramework/howtos/How_to_include_tcopen_in_a_project/article.html#1-create-a-new-c-class-library-project--net-standard-20-in-your-solution-and-name-it-plcprojectconnector) I get the following warning:

```
Warning	NU1701	Package 'TcOpen.TcoCoreConnector 0.5.0-alpha.834' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
```

When I create a C# project .NET 5.0 instead of .NET Standard 2.0 I get no warnings.

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10.0.19043 Build 19043
 - Microsoft Visual Studio Community 2019 Version 16.11.13
 - TwinCAT3 version  4024.29
- TcOpen.TcoCoreConnector 0.5.0-alpha.834

**Comment by PTKu** [comment]
Right, will need to discuss further how to deal with .netcore2.0 in this case... inxton supports officially net4.8 and net5.0 at this point...

**Comment by PTKu** [comment]
@rruiter87 changed the documentation to net48, net5 and net6
closing here, feel free to reopen if needed
