### ISSUE TITLE
TcoInspectors - multiple inspections

### ISSUE THREAD

**Issue by kuh0005** [TcOpenGroup/TcOpen#407]
Visibility of retry, abort, override tasks according minimal retry value. In case of overAttmepts => e.g. do not show dialog.

When any inspection failed is needed custom mechanic/logical operation in the same calling step. Can be \_currentRunResult member accesible through the property?

Dialog not visible - application start in the moment when sequence is suspended?

Add property for Count "out of range", Time Inside range, Time out of range

[#184] - internal issue

**Comment by PTKu** [comment]
> Visibility of retry, abort, override tasks according minimal retry value. In case of overAttmepts => e.g. do not show dialog.

Done with retries normalization in TcoGroupInspector in https://github.com/TcOpenGroup/TcOpen/pull/409

> 
> When any inspection failed is needed custom mechanic/logical operation in the same calling step. Can be _currentRunResult member accesible through the property?

won't do

> Dialog not visible - application start in the moment when sequence is suspended?

This may happed during commissioning when the app is opened and close frequently
opening separate issue for this here: https://github.com/TcOpenGroup/TcOpen/issues/413

> Add property for Count "out of range", Time Inside range, Time out of range

will do moved to separate issue here https://github.com/TcOpenGroup/TcOpen/issues/414

> 
> [#184] - internal issue
