### ISSUE TITLE
Idea: add link to docs in the project About

### ISSUE THREAD

**Issue by rruiter87** [TcOpenGroup/TcOpen#410]
Often I come to the TcOpen page looking for the documentation. Currently there is only one link, somewhere far down the README pointing to the docs. It would be nice to have the link directly in the About, like is also done for the docs repo https://github.com/TcOpenGroup/TcOpen.Documentation

**Comment by PTKu** [comment]
Thanks @rruiter87 
Like this?

![image](https://user-images.githubusercontent.com/61538034/170005360-71fc35fe-eabd-44d3-bf9b-ba123bbcaeee.png)

**Comment by rruiter87** [comment]
Yes!
