### ISSUE TITLE
[BUG] Multiple inspections -  Retry button is allowed/visible, inside inspection failed dialog when is over attempts

### ISSUE THREAD

**Issue by kuh0005** [TcOpenGroup/TcOpen#421]
**Describe the bug**
Retry button is allowed/visible, inside inspection failed dialog when is over attempts

![image](https://user-images.githubusercontent.com/676811/172117492-fbac790b-8669-4bb6-88a5-6f3ea2eb17a1.png)

![image](https://user-images.githubusercontent.com/676811/172117198-b64803f1-2a77-4c34-bfdc-14cadebebc66.png)

**Comment by PTKu** [comment]
@kuh0005 does this occurs in single inspection or only in grouped inspections?
