### ISSUE TITLE
[BUG] TcoData - Cannot search for entities saved in MongoDB with special characters saved in _EntityId

### ISSUE THREAD

**Issue by JurajSpisiak** [TcOpenGroup/TcOpen#424]
**Describe the bug**
When trying to search for entities in DB with prefix such as "(UTC)".

**To Reproduce**
1. Save entities in DB with prefix "(UTC)"
2. Try to search for created entities.

**Expected behavior**
You should be able to search for entities witch characters such as "+, (, ), /"..

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 11 Pro 21H2
 - Visual Studio version [e.g. Microsoft Visual Studio Professional 2019 Version 16.11.12]
 - TwinCAT3 version [eg. 4024.10]

**Comment by PTKu** [comment]
@JurajSpisiak do we use regex there? Would you have a look at it?
