### ISSUE TITLE
[FEATURE REQUEST] German localization request

### ISSUE THREAD

**Issue by sino32** [TcOpenGroup/TcOpen#455]
Please add the German localization.

**Comment by PTKu** [comment]
@sino32 when do you need it? Planned to end September (https://github.com/TcOpenGroup/TcOpen/milestone/3), if you need it sooner will reschedule.

@RGrabichler would you have a moment to help with German localization?

**Comment by RGrabichler** [comment]
Yes

**Comment by sino32** [comment]
Recommended schedule is fine
