### ISSUE TITLE
[NEW-FEATURE] Use only local assets for icons in Blazor

### ISSUE THREAD

**Issue by Specter-13** [TcOpenGroup/TcOpen#459]
When there is not internet connection, some icons won't load.
Update Blazor libraries to use only local assets for icons.

**Comment by PTKu** [comment]
@Specter-13 has this been addressed already? if where?

**Comment by Specter-13** [comment]
@PTKu yes, this PR should be closed, support for local assets was implemented in ivf version 1.15.9-alpha.722 and also in PR for TcoData and TcoDialogs.
