### ISSUE TITLE
[ENHANCEMENT]Logging out by user card 

### ISSUE THREAD

**Issue by rastislavsimak** [TcOpenGroup/TcOpen#468]
Logging out by using an already logged-in card stopped working.(Another card will log it out).

**Comment by PTKu** [comment]
The way this is implemented now is that the logout can be done manually (calling logout; pressing the logout method in the app) or by setting logout time, which will log out the user automatically after a preset time.

The idea would then be to log out the user when the logged user reads his own card (token) again?

**Comment by rastislavsimak** [comment]
Yes, the idea is to log out the user when the logged user rereads his card. This idea was working after implementation but after restarting the application stopped working.

**Comment by PTKu** [comment]
@rastislavsimak when do you need this to be fixed?

**Comment by rastislavsimak** [comment]
@PTKu  Im not sure, but its not urgent. We are still debugging the line.

**Comment by PTKu** [comment]
@rastislavsimak it is set to https://github.com/TcOpenGroup/TcOpen/milestone/3. Should you need it faster let us know.

**Comment by rastislavsimak** [comment]
okay, thank you.

**Comment by peterbarancek** [comment]
I would like to request for method **OnAuthenticating**. Something like this  I needed it in my application. There is OnUserAuthenticateSuccess but sometimes you need to check current user and compare with new one and do own scenario. By this  delegate is unable to cover a required customisation... Thanks
