### ISSUE TITLE
[BUG] TcoInspector.normalizeRetries()

### ISSUE THREAD

**Issue by KrisztianOlah** [TcOpenGroup/TcOpen#535]
**Describe the bug**
NormalizeRetries when called on 6 inspectors causes the TC compiler to take ages to compile, however, calling them on 4 or less inspectors don't seem to make much of an impact on the compile time.
This behaviour makes use unfeasible during the development phase or at all if updates are likely. It is of particular concern if multiple instances of such evaluators are required. Can be avoided by splitting inspections into separate evaluators, but then normalization might not take place correctly.
 
**To Reproduce**
1. Set up an evaluator with 6 different inspectors
2. Compile and time with stopwatch

**Expected behavior**
A slight increase in compile time, particularly when most objects are already compiled.

**Screenshots**
<img width="620" alt="image" src="https://user-images.githubusercontent.com/6548027/196427285-474ba02f-f2dd-4833-88c4-c71d9bc073e0.png">

**Desktop:**
 - OS: Win 11 Pro 21H2 22000.1098
 - Microsoft Visual Studio Professional 2019 Version 16.11.17
 - TwinCAT3 4024.22

**Comment by PTKu** [comment]
Should we report this to Beckohff :)? or rather CoDeSys?
@kuh0005 did you have similar issue, or maybe it is something particular project/configuration related?
Will have a look at the normalization method if I can spot something.

**Comment by KrisztianOlah** [comment]
I think so, when Blazej showed it to me I added them to all my multiple inspections then I started compiling and went for lunch when I came back it was still compiling/hanging. I have a pair of 6 and a pair of 4 inspectors on my last station.

**Comment by PTKu** [comment]
Similar issue was discovered by @mhareznik 
@mhareznik don't forget to report pls

**Comment by mhareznik** [comment]
Yes, I'm having a similar issue, in my case I'm calling Inspect method 12 times, without NormalizeRetries :
![image](https://user-images.githubusercontent.com/101903843/211536316-4323567a-5604-4932-8660-534ec12c5ddf.png)
This also leads to a never-ending (very long) compile time.

**Comment by KrisztianOlah** [comment]
Current workaround is to split Inspects into a group of maximum 5 and into multiple steps in sequence.
