### ISSUE TITLE
[BUG] VS crash TcOpen 

### ISSUE THREAD

**Issue by nico10hahn** [TcOpenGroup/TcOpen#546]
**Describe the bug**
Visual Studio crashes when compiling the TcOpen project from the introductory video ("TcOpen 101-1 Introduction to TcOpen framework TcoContext and TcoLogger (PLC + .NET C#)"). TcOpen.Group is installed via NuGet and the Inxton compiler is installed and licensed.

**To Reproduce**
1. Follow all instruction of the Video
2. Click Inxton-Vortex-Build

**Screenshots**
![VS_Crash_Inxton_Compiler](https://user-images.githubusercontent.com/116799962/198987840-a614f2cd-3282-4c62-81c6-27a641356ecf.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11 Pro 22H2 ]
 - Visual Studio: Microsoft Visual Studio Community 2019 version [Version 16.11.20]
 - TwinCAT3 version [v3.1.4024.35]
 - Microsoft .NET Framework Version 4.8.09032

**Comment by PTKu** [comment]
Hi @nico10hahn, Thanks for reporting!
I am unable to reproduce. It could be there is a problem with the language mutation of VS (de), the project was created in `en-US`. It gave us problems in the past (I suspect there is a problem searching the project tree `TcOpenPlc Projekt` vs `TcOpenPlc Project`). Would you be able to run VS in English, and let me know if the problem persists?

**Comment by nico10hahn** [comment]
Hello @PTKu, thanks for the reply. You were right, it works fine when VS is set to english. Many thanks for the help !

**Comment by PTKu** [comment]
Hi @nico10hahn when you create your solution in German mutation of VS it should work. Should you have troubles then let us know, we will dig deeper. 
Close or leave open this issue, at your discretion.
