### ISSUE TITLE
[NEW-FEATURE] Add support for safety(twinsafe)

### ISSUE THREAD

**Issue by Rednas83** [TcOpenGroup/TcOpen#552]
**Is your feature request related to a problem? Please describe.**
Are there also plans for supporting safety?

**Describe the solution you'd like**
A more automated way similar to sick/pilz.

**Describe alternatives you've considered**
Safety with sick/pilz

**Comment by PTKu** [comment]
Hi @Rednas83, thanks for the suggestion
Safety automation is out of the scope of this project. There are a few practical but also legal reasons that would make it a tricky endeavor.
