### ISSUE TITLE
[BUG] TcoTask.Busy is active prematurely, invoke needs to be called multiple times

### ISSUE THREAD

**Issue by mhareznik** [TcOpenGroup/TcOpen#577]

**Comment by mhareznik** [comment]
For more details:
Declaration of _parallelTask:
`_paralellTask : CU00xAutomatParalell_1_Task(THIS^, TcoCore.eRestoreMode.AutoRestoreMembers);`

Cyclic calling of _parallelTask in CU00xAutomatTask.Main method:
`_paralellTask();`

Invoking task in step of sequence:
`IF (Step(2004, TRUE, 'START PARALELL TASK')) THEN`
`//-------------------------------------`
`	StepCompleteWhen(_paralellTask.Task.Invoke().Busy);`
`//-------------------------------------`
`END_IF`

**Comment by PTKu** [comment]
You will need to use 'TcoCore.eRestoreMode.None' instead of 'TcoCore.eRestoreMode.AutoRestoreMembers', when you want to use the task asynchronously.

![image](https://user-images.githubusercontent.com/61538034/215492126-3ed2e72a-47a1-4030-9fb3-8a81bf485b13.png)
