### ISSUE TITLE
Inxton-Vortex builder naming bug

### ISSUE THREAD

**Issue by HeWhatMTS** [TcOpenGroup/TcOpen#586]
When you want create new solution or change name of your solution and you use the following syntax in the name: [space]-[dash] [space]  " - " after starting Inxton-Vortex builder it will not finish building fails with the following error message:
`ERR >>>>>>"E","","Failed to retrieve information from solution file 'C:\MTS\2022\2200689_CT_Presov\2200689_CENTER CONSOLE\project.template\2200689  - CENTER_CONSOLE.sln'","","","0","0"`

![Bugreport](https://user-images.githubusercontent.com/123955634/220044286-64e72c01-cfac-4fbc-bd16-7fb10512b801.PNG)

 - Visual Studio version [e.g. Microsoft Visual Studio Professional 2019 Version 16.11.23]
 - TwinCAT3 version [eg. 4024.22]

**Comment by PTKu** [comment]
Thanks for that. That might be a problem when searching ROT(Running object table). We need that to determine the running instance of VS to be able to attach to the process of VS and Automation Interface.

Workaround is to avoid the use of special characters. Use only alphanumeric characters for the solution name.

We will look at the possible solution in the next iteration of the inxton builder.
