### ISSUE TITLE
Configure GitHub actions to run builds on self-hosted agents.

### ISSUE THREAD

**Issue by PTKu** [TcOpenGroup/TcOpen#59]

**Comment by jozefchmelar** [comment]
@PTKu It's rather easy to setup the self-hosted runner...I tested it out on my PC and it works. 
I had some issues regarding 7zip on my PC, but it should not be a blocker.

https://github.com/TcOpenGroup/TcOpen/runs/2555243895?check_suite_focus=true

edit : I also had to allow actions created by GitHub and allow Marketplace actions by verified creators

**Comment by PTKu** [comment]
Looks good, tomorrow will get the hardware (#58), hope will have time to install it by the end of this week...
Let's keep this open until we can safely run on the dedicated agent.
