### ISSUE TITLE
components structure

### ISSUE THREAD

**Issue by runtimevic** [TcOpenGroup/TcOpen#60]
Hello, 
I think that all the components should have a certain structure, for example like the motion PTP axis that I have sent to Tomas
estructure components:
 .- Config o settings, 
.- Status, 
.-Commands, 
.-Diagnosis o error, 
.- Etc...
example:
    stControl: ST_AxisControl;
    stStatus: ST_AxisStatus;
    stConfig: ST_AxisConfig;
    stError: ST_AxisError;
    stInputs: ST_AxisInputs;

**Comment by PTKu** [comment]
discussion about this opened #61 
closing here.
