### ISSUE TITLE
[QUESTION]About the License of TcOpen

### ISSUE THREAD

**Issue by soup01Threes** [TcOpenGroup/TcOpen#602]
Dear Professional Team,

I saw the Prerequisites parts that by using TcOpen, a  free inxton developer licence is required:
https://docs.inxton.com/register
But the link is shown 404.
Is that mean the no need to register the license anymore?

Thanks and BR,

**Comment by PTKu** [comment]
No need to register anymore for v2.0.0 and later :)

**Comment by soup01Threes** [comment]
Thanks !! I will close this issue and sorry to ask so many question..
