### ISSUE TITLE
[Suggestions] Suggest UTC Now as standard Time Format, confused by logging times atm

### ISSUE THREAD

**Issue by RGrabichler** [TcOpenGroup/TcOpen#639]
In the Issues #519 ]New-Feature] Extended Diagnostics in Blazor, i tinker around with the TcoMessages, i i noticed a TimeStamp Issue.

![image](https://github.com/TcOpenGroup/TcOpen/assets/33341896/117790e4-4429-47bc-aead-686a26ec0ef9)
this is Timestamp logged in Console

![image](https://github.com/TcOpenGroup/TcOpen/assets/33341896/47db1ce3-a750-4f8b-88b9-eb9368c6aa63)
this is the Timestamp in the Plc

![image](https://github.com/TcOpenGroup/TcOpen/assets/33341896/d8a95c2d-01ed-4aff-bc8c-d848a5c2f118)
this is my local Timestamp in Germany and Summertime

![image](https://github.com/TcOpenGroup/TcOpen/assets/33341896/c0e1f1e0-70be-4297-bfcf-93e46181077f)
this is UTC

And this is a complete mess in my opinion.

I would suggest, to allways log in UTC, and everybody can display whatever he wants.

I only assume, the 15.50 timestamp comes from local Slovenia Time?  UTC+2 ? In difference to Berlin +1 ?

So in my opinion, the Logger should use per default UtcNow, the Connector should use UtcNow, and 
the Wpf or Blazor View can render whatever they want for the User, probably Utc with corresponding TimeZone.

**Comment by PTKu** [comment]
There should not be a time difference between the time zones you mention.

@TomKovac?

@RGrabichler could you check that you call time synch in your program for the context? Something like this:
https://github.com/TcOpenGroup/tcopen-app-templates/blob/ec2b13f96b091538887fa9851f5fe3d3adfcdeec/templates/mts-s-template/t/src/x_template_x-xae/x_template_xPlc/Technology/Technology.TcPOU#L109C1-L109C29

**Comment by RGrabichler** [comment]
![image](https://github.com/TcOpenGroup/TcOpen/assets/33341896/24954361-09d4-4ddf-8a43-9be4761342e6)
i call this here
![image](https://github.com/TcOpenGroup/TcOpen/assets/33341896/c5db0b26-f3a2-426f-af03-a66b8740c794)

this is the _rtc
![image](https://github.com/TcOpenGroup/TcOpen/assets/33341896/64592bb2-cc90-416d-a185-1269d410c45e)
But this is the logged message,
Timestamp  in [ ] is my local Timezone Timestamp Utc+1, in the Payload it is Utc+3

**Comment by PTKu** [comment]
You're right. It should be aligned... will have a look on Monday.

**Comment by PTKu** [comment]
We are unable to reproduce.
@RGrabichler, what are the region settings of your PLC (time-zone)?

**Comment by RGrabichler** [comment]
for me it is UTC+1, Berlin Time.

**Comment by PTKu** [comment]
Here's the fixed text:

"Same as me! 😊
Where do you run your Blazor server? Is it on the PLC, or is it hosted elsewhere? It appears that there might be a difference in the environment settings between where you run your server and the PLC.

You can try running it with the second argument, specifying the AMS ID of your server as follows: `app.RtcSynchronize(TRUE, 'YOUR_SERVER_AMS_ID', 60)` (An empty string indicates that it will synchronize with the local system)."

**Comment by PTKu** [comment]
Same as me! 😊
Where do you run your Blazor server? Is it on the PLC, or is it hosted elsewhere? It appears that there might be a difference in the environment settings between where you run your server and the PLC.

You can try running it with the second argument, specifying the AMS ID of your server as follows: `app.RtcSynchronize(TRUE, 'YOUR_SERVER_AMS_ID', 60)` (An empty string indicates that it will synchronize with the local system).

**Comment by RGrabichler** [comment]
ok, in this specific scenario, where i tinker with the Diagnosis Component, i use UmRT and blazor runs on local Dev Pc/
So presumably both run on UTC +1.

**Comment by PTKu** [comment]
It looks like that might be an issue with UmRT. 
Did you try:
```
You can try running it with the second argument, specifying the AMS ID of your server as follows: app.RtcSynchronize(TRUE, 'YOUR_SERVER_AMS_ID', 60) (An empty string indicates that it will synchronize with the local system).
```
?

**Comment by RGrabichler** [comment]
i tried, and i tried it with real hardware.
both have identical time settings
![image](https://github.com/TcOpenGroup/TcOpen/assets/33341896/d6aa3cf0-2400-4e66-979c-368c7cc4d0ae)
![image](https://github.com/TcOpenGroup/TcOpen/assets/33341896/c79734c9-9c07-4633-995a-da5a2c00efee)
![image](https://github.com/TcOpenGroup/TcOpen/assets/33341896/2e943288-870a-40d3-a5e3-9b9a59e14852)
this is AMS ID from dev PC, were i run the Blazor App atm

**Comment by PTKu** [comment]
@TomKovac any comment on this?

@RGrabichler sorry if you answered this question before, but what would be your correct local time in the example above?

@peterbarancek what time do we set to the TimeStamp in the messenger?

**Comment by peterbarancek** [comment]
"This is my output. I am running an app on my laptop. The time is synchronized with the PLC (as seen in the screenshot at the bottom right of the picture). It runs on .net48 and is a WPF application. In my opinion, the time difference might be due to using .net5 or Blazor..."

<img width="2036" alt="image" src="https://github.com/TcOpenGroup/TcOpen/assets/62284244/27ced102-7397-4cdf-a7e7-726c021be8ce">

<img width="498" alt="image" src="https://github.com/TcOpenGroup/TcOpen/assets/62284244/f21cee28-9f4a-4e98-9cd0-64c7c047a423">

**Comment by RGrabichler** [comment]
> @TomKovac any comment on this?
> 
> @RGrabichler sorry if you answered this question before, but what would be your correct local time in the example above?
> 
> @peterbarancek what time do we set to the TimeStamp in the messenger?

in this case, 21.44 was the right time.

**Comment by RGrabichler** [comment]
i tried a bit 
![image](https://github.com/TcOpenGroup/TcOpen/assets/33341896/376b328d-5fce-47de-b78c-6c9b24034614)
![image](https://github.com/TcOpenGroup/TcOpen/assets/33341896/26d77d89-ba4b-477f-9354-ccb132d1cdc2)
this is the ams ID from the PLC, manually changed the Clock to differ from real Time, to test it out.
![image](https://github.com/TcOpenGroup/TcOpen/assets/33341896/51ad4566-82aa-43d8-bf37-796e65150f16)

This is my Dev PC 
![image](https://github.com/TcOpenGroup/TcOpen/assets/33341896/5a5c5cbf-c498-4ed8-837b-edaa8024f166)
but this is not working, what am i doing wrong?
Time shows still Plc Time, even when i am setting AMS ID to Dev PC, where Blazor runs.

**Comment by PTKu** [comment]
@RGrabichler, the update rate is currently set to 60 seconds. If needed, you can modify the second parameter to decrease this rate.

Regarding the original issue, we've pinpointed the cause of the time discrepancy. Connector.NET5 utilizes a newer ADS driver that considers the time zone. Given that the PLC time is designated as UTC, when a value is read from the controller, it's adjusted to local time.

Regrettably, we don't have a straightforward solution for this predicament at the moment. Addressing it would necessitate modifications in the Inxton connector. Please note that this connector is in its experimental phase and isn't officially supported for a .NET 5 target. While we don't have immediate plans, we may consider making the necessary adjustments in future major Inxton releases, especially those after the TwinCAT 4026 launch.

**Comment by RGrabichler** [comment]
ok, im fine with that and can implement a workaround with manually adding or subracting hours :X
thanks for the effort
