### ISSUE TITLE
[BUG] Issue with the Retry Method in Inspectors

### ISSUE THREAD

**Issue by mhareznik** [TcOpenGroup/TcOpen#654]
It appears that the Retry method on Inspectors is not functioning as expected. Currently, after setting a finite number of retries, inspections continue indefinitely, potentially causing a loop in the process.

Example:
`Station.ProcessDataManager.Data.CU00x.BoltPresenceInspector.Data.FailureDescription:='BoltPresenceInspector error';`
`Station.ProcessDataManager.Data.CU00x.BoltPresenceInspector.WithCoordinator(THIS^)`
`  .Inspect(_inspectionResult)`
`  .UpdateComprehensiveResult(Station.ProcessDataManager.Data.EntityHeader.Results)`
`  .OnFail()`
`  .Retry(999);`

The expected behavior is that after a defined number of retries, the process should terminate, and the sequence should jump to the RESTORE_STEP_ID step.

**Comment by peterbarancek** [comment]
If  **NumberOfAllowedRetries** is equal zero,  number of  retries will be infinite, but if you define a limit(in example below is 100) , then you  can check property **OverInspected** and write your own scenario.

this may be solution :

IF (Step(1100, TRUE, 'SINGLE ANALOGUE INSPECTION')) THEN
    //-------------------------------------    
	Station.ProcessDataManager.Data.CU00x.BoltDimensionPresenceInspector.Data.FailureDescription:='BoltDimensionPresenceInspector error';
	Station.ProcessDataManager.Data.CU00x.BoltDimensionPresenceInspector.Data.NumberOfAllowedRetries:=100;
	IF NOT Station.ProcessDataManager.Data.CU00x.BoltDimensionPresenceInspector.OverInspected THEN
		
		Station.ProcessDataManager.Data.CU00x.BoltDimensionPresenceInspector.WithCoordinator(THIS^)
			.Inspect(_inspectionDimensionResult)
			.WithDescription()
			.UpdateComprehensiveResult(Station.ProcessDataManager.Data.EntityHeader.Results)
			.OnFail().Retry(1100);
	ELSE
		 RequestStep(RESTORE_STEP_ID);
	END_IF
    //-------------------------------------
END_IF
