### ISSUE TITLE
[NEW-FEATURE]Reorganize manual visual in SingleAxis, MultiAxis.... due too many scrolbars

### ISSUE THREAD

**Issue by peterbarancek** [TcOpenGroup/TcOpen#672]
What should be a default height of expander in components details view?

**Comment by AdamPitak** [comment]
This is actual view: 
![Capture](https://github.com/TcOpenGroup/TcOpen/assets/73422975/adda10f2-7d1f-4f76-8f9a-c846444c0488)

**Comment by AdamPitak** [comment]
Can we also have a possibility in Service mode, hide tasks that we do no need (or we cannot use them). I mean at least homing, move modulo, move velocity. Or all of them, move relative and absolute included.
