### ISSUE TITLE
[QUESTION] TcoCylinder.AbortMove

### ISSUE THREAD

**Issue by KrisztianOlah** [TcOpenGroup/TcOpen#678]
Is there any particular reason why TcoCylinder.AbortMove* methods need write access to their boolean arguments? If have to create a new variable reflecting the conditions (negation, etc.) then all details to the original signal is lost anyway, why can't it just take an input variable. An input variable would enable to pass in a complex boolean expression inline. Thanks

![Snapshot - 2024-16-1-09-48-11](https://github.com/TcOpenGroup/TcOpen/assets/6548027/7791eacf-081b-412b-8ea3-229782a0b715)

**Comment by peterbarancek** [comment]
Please check methods SuspendMoveHome() SuspendMoveHomeExpresion()....
