### ISSUE TITLE
[NEW-FEATURE] Selector view above Service view

### ISSUE THREAD

**Issue by KrisztianOlah** [TcOpenGroup/TcOpen#694]
Currently the service view does not have the selector like we had in Vortex. If one forgets to set the machine to manual mode it takes extra steps to resolve. See picture below:

![image](https://github.com/TcOpenGroup/TcOpen/assets/6548027/21277a82-26aa-407e-9bd5-ac56bb43f562)

Could we please have the following selector view added without the cycle time measurements:

![image](https://github.com/TcOpenGroup/TcOpen/assets/6548027/c7aad82b-c69a-4514-837e-b35a7dc81157)

Thanks.

**Comment by peterbarancek** [comment]
closed in template repository
