### ISSUE TITLE
[NEW-FEATURE] adding InPosition method into TcoDriveSimple

### ISSUE THREAD

**Issue by AdamPitak** [TcOpenGroup/TcOpen#704]
can you add into TcoDriveSimple

METHOD InPosition : BOOL
VAR_INPUT
	Position : LREAL;
	Window : LREAL;
END_VAR

InPosition := ABS(Axis._axisStatus.ActPos - Position) < Window;

**Comment by peterbarancek** [comment]
closes https://github.com/TcOpenGroup/TcOpen/issues/709
