### ISSUE TITLE
[NEW-FEATURE] Add method for suspend carousel based on expression

### ISSUE THREAD

**Issue by mhareznik** [TcOpenGroup/TcOpen#714]
I would like to request a new feature for the carousel component in TcoElements library. The proposed feature is to add a method that allows suspending the carousel based on a conditional parameter passed as VAR_INPUT, similar as in TcoCylinder function block.

**Comment by peterbarancek** [comment]
closes #712

**Comment by peterbarancek** [comment]
closes #712
