### ISSUE TITLE
[NEW-FEATURE] Add MC_TorqueControl

### ISSUE THREAD

**Issue by rruiter87** [TcOpenGroup/TcOpen#718]
Is it possible to add [`MC_TorqueControl`](https://infosys.beckhoff.com/content/1031/tcplclib_tc2_mc2/7617393803.html?id=228837685507697346) to TcOpen? I've started to add it to a project that I'm currently working on, but I find working with TcOpen quite overwhelming. 

I can open a PR with what I have so far, maybe you can provide some pointers on what is missing or things I did wrong.

**Comment by peterbarancek** [comment]
It is up to you. If you want, you can prepare your content and share with me. I will review it. Or wait  i will prepare it for you.

**Comment by rruiter87** [comment]
See #720 

I tried setting up the required development environment, but I can't download the visual studio 2019 community version installer anywhere. With Visual Studio 2022, the Inxton compiler plugin refused to install.

**Comment by KrisztianOlah** [comment]
Hi Roald, you can also use the inxton compiler from command line by
navigating to your solution path and typing
.\_Vortex\builder\vortex.compiler.console.exe -s  YOUR_SOLUTION_FILE.

Kind Regards
Kris

**Comment by rruiter87** [comment]
Thanks for implementing this so fast!
