### ISSUE TITLE
[QUESTION] What is the schedule for nuget releases?

### ISSUE THREAD

**Issue by rruiter87** [TcOpenGroup/TcOpen#723]
`MC_TorqueControl` was added with #722. I wondered when the next nuget alpha release is planned.

**Comment by peterbarancek** [comment]
Hi,
packages are published,  check here https://github.com/TcOpenGroup/TcOpen/releases/tag/0.11.0-alpha.73

**Comment by rruiter87** [comment]
Thanks :)

**Comment by rruiter87** [comment]
Is there a schedule, or are they released when there are enough new additions?

**Comment by peterbarancek** [comment]
They are released  on every addition into dev branch(nightly build publish them into dev feed). On nuget.org are published manually, usually after packages have been verified in the development pipeline.
