### ISSUE TITLE
[QUESTION] Is it possible to use TcUnit with TcOpen objects?

### ISSUE THREAD

**Issue by rruiter87** [TcOpenGroup/TcOpen#726]
Is there a way to use TcUnit with TcOpen objects? I now tried the following. I have this sensor I want to unit test, that derives from TcoComponent.

```
FUNCTION_BLOCK SomeSensor EXTENDS TcoCore.TcoComponent
...
```

When I instantiate it for the unit tests, I need to pass a reference to the parent object to it. But that doesn't compile.

```
FUNCTION_BLOCK LinearQuadraticRegulator_Tests EXTENDS FB_TestSuite
VAR
    /// either instatiate it here
    sensor : SomeSensor(THIS^);
END_VAR

METHOD TestInputValidation()
VAR_INST
    /// or here
    sensor : SomeSensor(THIS^);
END_VAR
```

I also tried to instantiate a TcoComponent in the sensor function block. But also this doesn't compile.

```
```
FUNCTION_BLOCK SomeSensor 
VAR 
    _core : TcoCore.TcoComponent(THIS^);
END_VAR
...
```

Is there a way to do this?

**Comment by RGrabichler** [comment]
Yes it is, PTKu showed me a way.
You have to Implement TcoCore.ITcoContext like that
```
FUNCTION_BLOCK LinearQuadraticRegulator_Tests EXTENDS TcUnit.FB_TestSuite IMPLEMENTS TcoCore.ITcoContext
VAR
  _nfContext : TcoCore.TcoContextNfCompatibility; //Context for TcOpen
END_VAR
```

Then Add a Implementation of this to the DUT.
![image](https://github.com/TcOpenGroup/TcOpen/assets/33341896/41ff753a-bebb-43f8-b0c4-0ac1ad11cbc8)

Add the Implementation like that
`Context := This^._nfContext;` etc..
Then u can proceed like always with the tests

**Comment by PTKu** [comment]
https://github.com/tcunit/TcUnit/discussions/199#discussioncomment-4315931

**Comment by rruiter87** [comment]
Thanks for the elaborate answer @PTKu!
