### ISSUE TITLE
[NEW-FEATURE] TcOpen Inspectors with Overinspect

### ISSUE THREAD

**Issue by AdamPitak** [TcOpenGroup/TcOpen#735]
Can we have in Inspectors in .Retry(SomeStepUid) feature that can handle Over Inspect 

I tried it to fix it in my step, but it do not work nicely, because Inspector is stuck at running state:

IF Data.OverInspected AND Data.Data.Result = TcoInspectors.eInspectorResult.Failed THEN
	ProcessData.IsFailed := TRUE;
	ProcessData.Data.EntityHeader.Results.Failures := Data.Data.FailureDescription;
	MS.RequestRestoreOrigin();
END_IF

**Comment by peterbarancek** [comment]
closed #754
