### ISSUE TITLE
Has anyone else had trouble with the runbuild powershell script?

### ISSUE THREAD

**Issue by rjgwatson** [TcOpenGroup/TcOpen#85]
I have gone through the instructions for setting up the development environment on my host machine and a fresh VM and I get a lot of errors in the CopyInxton stage and the GitVersion state and my build fails.

I have attached the log file from my most recent attempt in a VM. Am I missing a step here?

[PS Build Log.txt](https://github.com/TcOpenGroup/TcOpen/files/6488149/PS.Build.Log.txt)

**Comment by PTKu** [comment]
could you download this https://github.com/GitTools/GitVersion/releases/download/5.5.0/gitversion-win-x64-5.5.0.tar.gz
unpack into 'C:\Users\richa\Documents\GitHub\TcOpen\_toolz\GitVersion.exe' 
and try to run script again

we will check that... and fix the script...

Let me know if that helps. Thanks
Creating an issue for that #86 

you can temporarily remove GitVersion section  from the script. It should look like this
~~~
﻿properties {
  $buildConfig = "Release"
  $isTestingEnabled = $false
  $msbuildVerbosity = "minimal"
  $baseDir  = resolve-path ..
  $solutionDir = "$baseDir\"
  $nugetSource = "https://api.nuget.org/v3/index.json"
  $nugetToken = ([System.Environment]::GetEnvironmentVariable('TcoOpenNugetdotorgPAT'))
  $publishNugets = $false
  $updateAssemblyInfo = $false
  $gitVersion
  $msbuild = ([System.Environment]::GetEnvironmentVariable('TcoMsbuild'))
  $dotnet = ([System.Environment]::GetEnvironmentVariable('TcoDotnet'))
  $devenv = ([System.Environment]::GetEnvironmentVariable('TcoDevenv'))
  $testTargetAmsId = ([System.Environment]::GetEnvironmentVariable('Tc3Target'))
  $testingStrength = 0
}



task default -depends CloseVs, Tests, CreatePackages, Finish


FormatTaskName (("="*25) + " [ {0} ] " + ("="*25))

task Init {
  Write-Host "Setting location to $baseDir"
  Set-Location $baseDir  
  $psake.context.Peek().properties
  $properties
}



task BuildScripts -continueOnError -depends Init {  
  Push-Location .\pipelines
  Import-Module .\tcobuildutils.psm1 -Force -Verbose 
  Pop-Location
}

task Start -depends BuildScripts {
  #Assert $gitOK "[📩] Please commit your changes before running build"
} 

task Clean -depends Start {
  Write-Host "Clean obj bin"
  CleanObjBin
  RemoveTcBins
  RemoveTcProjBins
  RemoveGenerated
  RemoveMeta
  mkdir .\_Vortex\builder -ErrorAction SilentlyContinue 
  mkdir .\.nuget -ErrorAction SilentlyContinue 
  mkdir .\_toolz -ErrorAction SilentlyContinue 
  mkdir .\nugets -ErrorAction SilentlyContinue
  mkdir .\nugets\dependants -ErrorAction SilentlyContinue
}
 
task NugetRestore -depends Clean {
   EnsureNuget

   exec{
       & $dotnet restore TcOpen.build.slnf
   }
} 

task CopyInxton -depends NugetRestore -continueOnError {
  exec {
      & $dotnet build `
        .\src\TcoApplicationExamples\PlcAppExamplesConnector\PlcAppExamplesConnector.csproj `
        /p:SolutionDir=$solutionDir
  }
}

task GitVersion -depends CopyInxton {
}

task OpenVisualStudio -depends GitVersion {
  Start-Process .\TcOpen.plc.slnf
}


task BuildWithInxtonBuilder -depends OpenVisualStudio {

  $command = ".\_Vortex\builder\vortex.compiler.console.exe -s .\TcOpen.plc.slnf"

  Write-Host $command
   exec { 
      cmd /c $command
  }       

  # $projects = @(  
  #    "src\Tc.Prober\Tc.Prober.slnf",   
  #    "src\TcoCore\TcoCore.slnf",
  #    "src\TcoDrivesBeckhoff\TcoDrivesBeckhoff.slnf",
  #    "src\TcoIoBeckhoff\TcoIoBeckhoff.slnf",
  #    "src\TcoPneumatics\TcoPneumatics.slnf"
  #    "src\TcoElements\TcoElements.slnf",
  #    "src\TcoApplicationExamples\TcoApplicationExamples.slnf",
  #    "src\librarytemplate\PlcTemplate.slnf"
  #  )

  #  foreach($project in $projects)
  # {   
  #   $command = ".\_Vortex\builder\vortex.compiler.console.exe -s " + $project
  #   Write-Host $command
  #   exec { 
  #     cmd /c $command
  #   }       
  # }

}

task Build -depends BuildWithInxtonBuilder {
  #/consoleloggerparameters:ErrorsOnly  
  Write-Host $command
  exec{
     & $msbuild .\TcOpen.build.slnf `
        /p:Configuration=$buildConfig `
        -noWarn:"CS1591;CS0067;CS0108;CS1570" `
        /consoleloggerparameters:ErrorsOnly `
        -v:$msbuildVerbosity    
  }
}


task CloseVs -depends Build {
  exec{
    Get-Process devenv | Stop-Process -ErrorAction SilentlyContinue
  }
}


task Tests -depends CloseVs  -precondition { return $isTestingEnabled } {

    Set-Location $baseDir 

    Write-Host '--------------------------------------------' -ForegroundColor Cyan
    Write-Host 'Building plc projects' -ForegroundColor Cyan
    Write-Host '--------------------------------------------' -ForegroundColor Cyan

    $command = "`"$devenv`" .\TcOpen.test.build.plc.slnf /Rebuild " + "`"$buildConfig|TwinCAT RT (x64)`""
      
    exec{
        cmd /c $command
    }
        	
    $testProjects = @(                    
                      [System.Tuple]::Create(".\src\TcoCore\TcoCore.slnf", "\src\TcoCore\src\XaeTcoCore\", -1, "TcoCore"),                     
                      [System.Tuple]::Create(".\src\TcoElements\TcoElements.slnf", ".\src\TcoElements\src\XAE\XAE\", -1, "TcoElements"),
                      [System.Tuple]::Create(".\src\TcoIoBeckhoff\TcoIoBeckhoff.slnf", "\src\TcoIoBeckhoff\src\XaeTcoIoBeckhoff\", -1, "TcoIoBeckhoff"),
                      [System.Tuple]::Create(".\src\TcoPneumatics\TcoPneumatics.slnf", "src\TcoPneumatics\src\XaeTcoPneumatics\", -1, "TcoPneumatics")                     
                    )
                    # removed due to missing hardware  
                    # [System.Tuple]::Create(".\src\TcoDrivesBeckhoff\TcoDrivesBeckhoff.slnf", "\src\TcoDrivesBeckhoff\src\XaeTcoDrivesBeckhoff\", -1, "TcoDrivesBeckhoff"),

    Write-Host "Running tests up to strength $testingStrength"

    foreach ($testProject in $testProjects) 
    {  
      $testProjectOrSolution =  $testProject.Item1;  
      $xaeProjectFolder =  $testProject.Item2;           
      $tier =  $testProject.Item3;
      $projName = $testProject.Item4;


      if($tier -le $testingStrength)
      {      
        Write-Host '--------------------------------------------' -ForegroundColor Cyan
        Write-Host "Running test for $testProjectOrSolution | plc: $xaeProjectFolder" -ForegroundColor Cyan
        Write-Host '--------------------------------------------' -ForegroundColor Cyan

       
        if($xaeProjectFolder -ne "")
        {
          Start-Sleep 5
          .\pipelines\utils\CleanupTargetBoot.ps1 $testTargetAmsId;
          Start-Sleep 5
          $BootDir = $solutionDir + $xaeProjectFolder;               
          .\pipelines\utils\Load-XaeProject.ps1 $testTargetAmsId $BootDir;                    
          Start-Sleep 5
        }


        $LogFileName = "TEST-$projName.xml"
        exec{   
          & $dotnet test $testProjectOrSolution `
            -c $buildConfig `
            -f net48 `
            -v $msbuildVerbosity `
            -l:"trx;LogFileName=$LogFileName" `
            --no-build `
            --no-restore
        }

       
      }
      else {
        Write-Host '--------------------------------------------' -ForegroundColor Yellow
        Write-Host "Skipping tests for $testProjectOrSolution due to testing strenght settings $tier -le $testingStrength" -ForegroundColor Yellow
        Write-Host '--------------------------------------------' -ForegroundColor Yellow
      }    
    }
} 


task ClearPackages -depends Tests {
  mkdir nugets -ErrorAction SilentlyContinue
  mkdir nugets\dependants -ErrorAction SilentlyContinue
  Get-ChildItem -Path .\nugets\ -Include *.* -File -Recurse | ForEach-Object { $_.Delete()}
}

task CreatePackages -depends ClearPackages {
  $semVer = $script:gitVersion.SemVer
  $projects = @(
    #Packaging
    "src\TcoCore\src\TcoCore.Wpf\TcoCore.Wpf.csproj",
    "src\TcoCore\src\TcoCoreConnector\TcoCoreConnector.csproj",
    "src\TcoDrivesBeckhoff\src\TcoDrivesBeckhoff.Wpf\TcoDrivesBeckhoff.Wpf.csproj",
    "src\TcoDrivesBeckhoff\src\TcoDrivesBeckhoffConnector\TcoDrivesBeckhoffConnector.csproj",
    "src\TcoIoBeckhoff\src\TcoIoBeckhoff.Wpf\TcoIoBeckhoff.Wpf.csproj",
    "src\TcoIoBeckhoff\src\TcoIoBeckhoffConnector\TcoIoBeckhoffConnector.csproj",
    "src\TcoPneumatics\src\TcoPneumatics.Wpf\TcoPneumatics.Wpf.csproj",
    "src\TcoPneumatics\src\TcoPneumaticsConnector\TcoPneumaticsConnector.csproj"   
  )
  foreach($project in $projects)
  {  
    exec { 
       & $dotnet pack $project -p:PackageVersion=$semVer --output nugets -c $buildConfig /p:SolutionDir=$solutionDir -v $msbuildVerbosity --no-restore --no-build
    }
  }
}

task PublishPackages -depends CreatePackages -precondition {return $publishNugets} {
  Write-Host "About to" 
  PushNugets -folderWithNugets .\nugets -token $nugetToken -source $nugetSource
}

task Finish -depends PublishPackages {
  Write-Host "Done"
} 


~~~

**Comment by rjgwatson** [comment]
Thanks, that gets me around the previous issue. btw you accidentally left a } here:

>   #(GitVersionToPlcVersion $script:gitVersion)
  if( $updateAssemblyInfo){.\_Vortex\builder\uvn.exe -v $plcversion}
}

The next issue that seems to come up is that It looks like the .library files for TcoCore etc are not located in the expected directories (I am unable to find them anywhere):

> C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targe
ts(4919,5): error MSB3030: Could not copy the file "C:\Users\richa\Documents\GitHub\TcOpen\src\TcoCore\src\TcoCoreConne
ctor\_meta\TcoCore.library" because it was not found. [C:\Users\richa\Documents\GitHub\TcOpen\src\TcoCore\src\TcoCoreCo
nnector\TcoCoreConnector.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targe
ts(4919,5): error MSB3030: Could not copy the file "C:\Users\richa\Documents\GitHub\TcOpen\src\TcoCore\src\TcoCoreConne
ctor\_meta\version.info" because it was not found. [C:\Users\richa\Documents\GitHub\TcOpen\src\TcoCore\src\TcoCoreConne
ctor\TcoCoreConnector.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targe
ts(4919,5): error MSB3030: Could not copy the file "C:\Users\richa\Documents\GitHub\TcOpen\src\TcoCore\src\TcoCoreConne
ctor\_meta\TcoCore.library" because it was not found. [C:\Users\richa\Documents\GitHub\TcOpen\src\TcoCore\src\TcoCoreCo
nnector\TcoCoreConnector.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targe
ts(4919,5): error MSB3030: Could not copy the file "C:\Users\richa\Documents\GitHub\TcOpen\src\TcoCore\src\TcoCoreConne
ctor\_meta\version.info" because it was not found. [C:\Users\richa\Documents\GitHub\TcOpen\src\TcoCore\src\TcoCoreConne
ctor\TcoCoreConnector.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targe
ts(4919,5): error MSB3030: Could not copy the file "C:\Users\richa\Documents\GitHub\TcOpen\src\TcoIoBeckhoff\src\TcoIoB
eckhoffConnector\_meta\TcoIoBeckhoff.library" because it was not found. [C:\Users\richa\Documents\GitHub\TcOpen\src\Tco
IoBeckhoff\src\TcoIoBeckhoffConnector\TcoIoBeckhoffConnector.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targe
ts(4919,5): error MSB3030: Could not copy the file "C:\Users\richa\Documents\GitHub\TcOpen\src\TcoIoBeckhoff\src\TcoIoB
eckhoffConnector\_meta\TcoIoBeckhoff.library" because it was not found. [C:\Users\richa\Documents\GitHub\TcOpen\src\Tco
IoBeckhoff\src\TcoIoBeckhoffConnector\TcoIoBeckhoffConnector.csproj]
Error: 15/05/2021 22:16:03:
  .     -v:$msbuildVerbosity    :ErrorsOnly ` `~~~~ [<<==>>] Exception: Exec: Error executing command
build.ps1 failed

**Comment by PTKu** [comment]
>Thanks, that gets me around the previous issue. btw you accidentally left a } here:

>>#(GitVersionToPlcVersion $script:gitVersion)
>>if( $updateAssemblyInfo){._Vortex\builder\uvn.exe -v $plcversion}
>>}

Thanks! I fixed that above, sorry for that:)

Could you post the entire log like before? 

The script should look something like this  under 'Run a multi-line script' https://github.com/TcOpenGroup/TcOpen/runs/2582680982?check_suite_focus=true

It looks like there was some problem creating libraries for some reason. 
Few questions:

- Did the script open Visual Studio (there should be only one instance running)?

- Can you locate file 'C:\Users\richa\Documents\GitHub\TcOpen\_Vortex\builder\vortex.compiler.console.exe'?

- Can you try to run the following?

~~~PowerShell
cd C:\Users\richa\Documents\GitHub\TcOpen
Start-Process .\TcOpen.plc.slnf
.\_Vortex\builder\vortex.compiler.console.exe -s TcOpen.sln
~~~

Thanks for reporting! Let me know please how did that go.

**Comment by rjgwatson** [comment]
Strangely, when I ran the script again without doing anything the libraries installed properly. I am not sure what happened last time, but I know that I didn't have Visual Studio open, and one instance opened when I ran the script, so I am not sure what happened before. 

I now get the following error which stops the installation:

> C:\Program Files\dotnet\sdk\5.0.203\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(110,5): error MSB4044: The "GetPackOutputItemsTask" task was not given a value for the required parameter "PackageVersion". [C:\Users\richa\Documents\GitHub\TcOpen\src\TcoCore\src\TcoCore.Wpf\TcoCore.Wpf.csproj]
Error: 16/05/2021 10:01:31:
       & $dotnet pack $project -p:PackageVersion=$semVer --output nugets -c $buildConfig /p:SolutionDir=$solutionDir -v     .ildVerbosity --no-restore --no-build
build.ps1 failed

I have attached the full log this time.
[PS Build Log 210516-1003.txt](https://github.com/TcOpenGroup/TcOpen/files/6488935/PS.Build.Log.210516-1003.txt)

**Comment by PTKu** [comment]
OK It failed at 'Create packages' that is not necessary for you to continue, that step only prepares the nuget packages for publishing on a feed. The reason why it failed is because we are missing `p:PackageVersion=$semVer` variable that comes from GitVersion step we removed. But you can ignore that.... you really do not need those packages.

Now you should be able to open and work with `sln` (entire solution) or any `slnf` (filtered solutions) files. We will simplify the getting-started script next week #87.  The script in use is doing too many things, it is basically whole pipeline from build to release...

Thanks for reporting again!

**Comment by rjgwatson** [comment]
Thanks for the help! It looks like everything is as it should be now.
