### ISSUE TITLE
Fix build script GitVersion. Looking for the executable at wrong place #85

### ISSUE THREAD

**Issue by PTKu** [TcOpenGroup/TcOpen#86]
@jozefchmelar  Same issue we had when installing the agents with the GitVersion path. Let's just skip versioning when 'updateAssemblyInfo' is false.
See #85 

We should also call build on a connector project on a dummy project without partial extensions.

**Comment by jozefchmelar** [comment]
We're already doing a build on a connector project without partial extension 
```
.\src\TcoApplicationExamples\PlcAppExamplesConnector\PlcAppExamplesConnector.csproj 
```

Btw the PR #90

**Comment by PTKu** [comment]
> We're already doing a build on a connector project without partial extension
> 
> ```
> .\src\TcoApplicationExamples\PlcAppExamplesConnector\PlcAppExamplesConnector.csproj 
> ```
> 
> Btw the PR #90

@jozefchmelar yes... but that project has dependencies that we also build, and there are partial extensions, that's why we get errors in the script...

**Comment by jozefchmelar** [comment]
@PTKu  yeah you got a point. I updated it in #93 , we can continue there.
