### ISSUE TITLE
Create simplified the getting-started build script. 

### ISSUE THREAD

**Issue by PTKu** [TcOpenGroup/TcOpen#87]
Build and release script is too heavy and there are too many dependencies on the particular configuration/environment. We should run only restore/build ivc and solution build to retrieve dependencies and build solution...
see #85 

- [ ] Default does not create packages (if 'publishPackages == false' do not create packages)
- [ ] Default does not calcs semver (if 'updateAssemblyInfo == false' do not use GitVersion, nor download)

**Comment by jozefchmelar** [comment]
#90
